cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart"),
    path('success/', views.success, name="success"),
]

nhom3/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('vendor/', include('vendor.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('post/', include('post.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from . import views
from django.urls import path



app_name = 'product'


urlpatterns = [
    path('search', views.search, name="search"),
    path('brand/<slug:brand_slug>/', views.brand, name="brand"),
    path('<slug:category_slug>/<slug:product_slug>/', views.product, name="product"),
    path('<slug:category_slug>/', views.category, name="category"),

    
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.forms.fields import CharField 

class CheckoutForm(forms.Form):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    phone = forms.CharField(max_length=255)
    address = forms.CharField(max_length=255)
    zipcode = forms.CharField(max_length=255)
    place = forms.CharField(max_length=255)
    stripe_token = forms.CharField(max_length=255)


    

cart/views.py
import stripe #pip install stripe 

from django. conf import settings
from django.contrib import messages
from django.shortcuts import redirect, render
from .cart import Cart
from .forms import CheckoutForm

from order.utilities import checkout, notify_vendor, notify_customer

# Create your views here.
def cart_detail(request):
    cart = Cart(request)

    # If Checkout
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            stripe.api_key = settings.STRIPE_SECRET_KEY

            stripe_token = form.cleaned_data['stripe_token']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            address = form.cleaned_data['address']
            zipcode = form.cleaned_data['zipcode']
            place = form.cleaned_data['place']
            vendor = request.user.id
            order = checkout(request, first_name, last_name, email, phone, address, zipcode, place, cart.get_total_cost(),vendor)    
            cart.clear()
            notify_customer(order)
            notify_vendor(order)

            return redirect('cart:success')

    else:
        form = CheckoutForm()

    remove_from_cart = request.GET.get('remove_from_cart', '')
    change_quantity = request.GET.get('change_quantity', '')
    quantity = request.GET.get('quantity', 0)

    if remove_from_cart:
        cart.remove(remove_from_cart)
        return redirect('cart:cart')
    
    if change_quantity:
        cart.add(change_quantity, quantity, True)
        return redirect('cart:cart')
        
    return render(request, 'cart/cart.html', {'form': form, 'stripe_pub_key': settings.STRIPE_PUB_KEY})


def success(request):
    return render(request, 'cart/success.html')

templates/cart/cart.html
{% extends 'core/base.html' %}

{% block title %}Cart{% endblock title %}

{% block content %}

    <h1 class="title">Cart</h1>

    {% if cart %}
    
        <div class="box mb-6">
            <div class="table">
                <table class="table is-fullwidth is-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Sản phẩm</th>
                            <th>Số lượng</th>
                            <th>Giá</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for item in cart %}
                        
                            <tr>
                                <td>
                                    <figure class="image is-64x64">
                                        <img src="{{ item.product.image.url }}" alt="{{item.product.title}}">
                                    </figure>
                                </td>
                                <td>
                                    <a href="{% url 'product:product' item.product.category.slug item.product.slug %}">{{item.product.title}}</a>
                                </td>
                                <td>
                                    {{item.quantity}}

                                    <a href="?change_quantity={{ item.id }}&quantity=-1">-</a>
                                    <a href="?change_quantity={{ item.id }}&quantity=1">+</a>

                                </td>

                                <td>{{ item.total_price }} VNĐ</td>
                                <td>
                                    <a href="?remove_from_cart={{item.id}}" class="delete">Xóa</a>
                                </td>
                            </tr>
                        
                        {% endfor %}
                    </tbody>

                    <tfoot>
                        <tr>
                            <td></td>
                            <td><strong>Thành tiền</strong> </td>
                            <td><strong>{{ cart|length }}</strong> </td>
                            <td colspan="2" style="color:red"><b></b></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>


        <h2 class="subtitle">Contact Information</h2>

        <form method="post" action="" id="payment-form">
            {% csrf_token %}

            {% if form.non_field_errors %}
                <div class="notification is-danger">
                    {{form.non_field_errors}}
                </div>
            {% endif %}

            {% if form.errors %}
                <div class="notification is-danger">
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li><strong>{{field.label}}</strong>{{error}}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <div class="columns">
                <div class="column is-6">
                    <div class="field">
                        <label>First Name</label>

                        <div class="control">
                            <input type="text" name="first_name" id="" class="input">
                        </div>
                    </div>

                    <div class="field">
                        <label>Last Name</label>

                        <div class="control">
                            <input type="text" name="last_name" id="" class="input">
                        </div>
                    </div>

                    <div class="field">
                        <label>Email</label>

                        <div class="control">
                            <input type="email" name="email" id="" class="input">
                        </div>
                    </div>

                    <div class="field">
                        <label>Phone</label>

                        <div class="control">
                            <input type="text" name="phone" id="" class="input">
                        </div>
                    </div>

                </div>

                <div class="column is-6">
                    <div class="field">
                        <label>Address</label>

                        <div class="control">
                            <input type="text" name="address" id="" class="input">
                        </div>
                    </div>

                    <div class="field">
                        <label>Zip Code</label>

                        <div class="control">
                            <input type="text" name="zipcode" id="" class="input">
                        </div>
                    </div>

                    <div class="field">
                        <label>Place</label>

                        <div class="control">
                            <input type="text" name="place" id="" class="input">
                        </div>
                        <input type="hidden" name="stripe_token" value="1">
                        <input type="hidden" name="cardnumber" value="1">
                    </div>

                </div>

            </div>


            <h2 class="subtitle">Payment Information</h2>

            
            {% if messages %}
                {% for message in messages %}
                    <div class="notification is-danger">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="field">
                <div class="control">
                    <button class="button is-dark mt-4 is-uppercase">Checkout</button>
                </div>
            </div>
        </form>
    {% else %}

    <p>You don't have any products in your cart.</p>

    {% endif %}

{% endblock content %}


{% block scripts %}

    <script src="https://js.stripe.com/v3/"></script>
    <script>
        var stripe = Stripe('{{ stripe_pub_key }}');
        var elements = stripe.elements();

        var card = elements.create('card');

        card.mount('#card-element');

        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function(event) {
            event.preventDefault();

            stripe.createToken(card).then(function(result) {
                if (result.error) {
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    stripeTokenHandler(result.token);
                }
            });
        });

        function stripeTokenHandler(token) {
            var form = document.getElementById('payment-form');
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'stripe_token');
            hiddenInput.setAttribute('value', token.id);
            form.appendChild(hiddenInput);

            form.submit();
        }
    </script>

{% endblock scripts %}

templates/cart/success.html
{% extends 'core/base.html' %}


{% block content %}

    <h1 class="title">Cảm ơn bạn đã mua hàng!</h1>

{% endblock content %}