cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart"),
    path('success/', views.success, name="success"),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.frontpage, name="home"),
    path('contact-us/', views.contactpage, name="contact"),
]

nhom3/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('vendor/', include('vendor.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('post/', include('post.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from . import views
from django.urls import path


app_name = 'post'


urlpatterns = [
     path('<slug:category_slug>/', views.category, name="category"),
]

product/urls.py
from . import views
from django.urls import path



app_name = 'product'


urlpatterns = [
    path('search', views.search, name="search"),
    path('brand/<slug:brand_slug>/', views.brand, name="brand"),
    path('<slug:category_slug>/<slug:product_slug>/', views.product, name="product"),
    path('<slug:category_slug>/', views.category, name="category"),

    
]

core/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.
class cate_post(models.Model):
    cate_post_name = models.CharField(max_length=255)
    cate_post_slug = models.SlugField(max_length=255, default=None)
    def __str__(self):
        return self.cate_post_name 

class post(models.Model):
    post_name = models.CharField(max_length=255)
    post_content= models.TextField(max_length=255)
    post_image = models.ImageField(upload_to="images", null=False, default=None)
    post_author = models.CharField(max_length=255)
    post_slug = models.SlugField(max_length=255, default=None)
    cate_post_id = models.ForeignKey(cate_post,related_name='posts', on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.post_name},{self.post_content},{self.post_image},{self.post_author}" 

core/views.py
from django.shortcuts import render
from product.models import Product

# Create your views here.

def frontpage(request):
    newest_products = Product.objects.order_by('id')[0:8]
    hot_product = Product.objects.all()[0:8]
    context = {
        'newest_products': newest_products,
        'hot_product': hot_product,
    }
    return render(request, 'core/frontpage.html', context)


def contactpage(request):
    return render(request, 'core/contact.html')

post/views.py
from django.shortcuts import render
from .models import cate_post, post
from django.shortcuts import redirect, render, get_object_or_404


# Create your views here.

def category(request, category_slug):
    category = get_object_or_404(cate_post, cate_post_slug=category_slug)
    posts= post.objects.filter(cate_post_id=category.id)
    return render(request,'product/cate_post.html', {'category': category,'posts':posts})

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>SHOP NHOM3</title>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css"/>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="http://cdn.bootcss.com/toastr.js/latest/css/toastr.min.css">
      <link rel="stylesheet" href="{% static 'css/main.css' %}" />
      <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js" ></script>
      <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js" ></script>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   </head>
   <body>

    <div class="container">
       <nav class="navbar navbar-expand-lg navbar-light" style="position: sticky;">
         <a class="navbar-brand" href="#"><img src="/static/image/logo.svg" style="width: 100%; height: 5rem" /></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
               <li class="nav-item active">
                  <a class="nav-link" href="{% url 'core:home' %}">Trang chủ</a>
               </li>
      
               <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Danh mục
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                     {% for category in categories %}
                        <a class="navbar-item" href="{% url 'product:category' category.slug %}">{{category.title}}</a>
                        {% endfor %}

                  </div>
               </li>

               <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Thương hiệu
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                     {% for brand in brands %}
                        <a class="navbar-item" href="/product/brand/{{brand.slug}}">{{brand.title}}</a>
                        {% endfor %}

                  </div>
               </li>

               <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Tin tức
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                     {% for cate in cate_posts %}
                        <a class="navbar-item" href="{% url 'post:category' cate.cate_post_slug %}">{{cate.cate_post_name}}</a>
                        {% endfor %}

                  </div>
               </li>

               <li class="nav-item active">
                  <a class="nav-link" href="{% url 'core:home' %}">Liên hệ</a>
               </li>
               
            </ul>
            <form method="get" action="{% url 'product:search' %}">
                        <div class="field has-addons">
                           <div class="control">
                              <input
                                 type="search"
                                 name="query"
                                 id=""
                                 class="input"
                                 placeholder="Search..."
                                 />
                           </div>
                           <div class="control">
                              <button class="button is-dark is-uppercase">Tìm kiếm</button>
                           </div>
                        </div>
                     </form>
                     <div class="navbar-end">
                  <div class="navbar-item">
                     <a href="{% url 'cart:cart' %}" class="button is-warning"
                        >Giỏ hàng {% if cart %}({{cart|length}}){% endif %}</a
                        >
                  </div>
                  {% if request.user.is_authenticated %}
                  <div class="navbar-item has-dropdown is-hoverable">
                     <a class="navbar-link is-capitalized"> {{request.user}} </a>
                     <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'vendor:vendor-admin' %}">
                        Thông tin
                        </a>

                        <hr class="navbar-divider" />
                        <a class="navbar-item" href="{% url 'vendor:logout' %}">
                        Đăng xuất
                        </a>
                     </div>
                  </div>
                  {% else %}
                  <div class="navbar-item">
                     <div class="buttons">
                        <a
                           class="button is-primary"
                           href="{% url 'vendor:register' %}"
                           >
                        <strong>Đăng ký</strong>
                        </a>
                        <a class="button is-light" href="{% url 'vendor:login' %}">
                        Đăng nhập
                        </a>
                     </div>
                  </div>
                  {% endif %}
               </div>
         </div>
      </nav>
    </div>

      <section class="section">
        <div class="container">
          {% block content %}
          {% endblock content %}
        </div>
      </section>

      <footer class="footer">
         <div
            class="footer-container"
            style="
            display: grid;
            grid-template-columns: 1.5fr repeat(4, 1fr);
            margin: 0 5rem;
            "
            >
            <div>
               <a href="#" class="footer-logo">
               <img
                  class="logo"
                  alt="Omnifood logo"
                  src="/static/image/logo.svg"
                  style="width: 10rem; height: 8rem, over-fit:cover"
                  />
               </a>
               <ul style="display: flex; gap: 2.5rem">
                  <li>
                     <a class="footer-link" href="#"
                        >
                        <ion-icon class="social-icon" name="logo-instagram"></ion-icon
                           >
                     </a>
                  </li>
                  <li>
                     <a class="footer-link" href="#"
                        >
                        <ion-icon class="social-icon" name="logo-facebook"></ion-icon
                           >
                     </a>
                  </li>
                  <li>
                     <a class="footer-link" href="#"
                        >
                        <ion-icon class="social-icon" name="logo-twitter"></ion-icon
                           >
                     </a>
                  </li>
               </ul>
               <p class="copyright">
                  Copyright &copy;<span class="year"></span> by N3, Inc. All rights
                  reserved.
               </p>
            </div>
            <div style="margin-right: 1rem">
               <p class="footer-heading">Contact us</p>
               <address class="contacts">
                  <p class="address">
                     PTIT-POST AND TELECOMMUNICATIONS INSTITUTE OF TECHNOLOGY
                  </p>
                  <p>
                     <a class="footer-link" href="tel:415-201-6370">0123456789</a
                        ><br />
                     <a class="footer-link" href="mailto:hello@n3.com">hello@n3.com</a>
                  </p>
               </address>
            </div>
            <nav class="nav-col">
               <p class="footer-heading">Account</p>
               <ul class="footer-nav">
                  <li><a class="footer-link" href="#">Create account</a></li>
                  <li><a class="footer-link" href="#">Sign in</a></li>
                  <li><a class="footer-link" href="#">iOS app</a></li>
                  <li><a class="footer-link" href="#">Android app</a></li>
               </ul>
            </nav>
            <nav class="nav-col">
               <p class="footer-heading">Company</p>
               <ul class="footer-nav">
                  <li><a class="footer-link" href="#">About N3Crown</a></li>
                  <li><a class="footer-link" href="#">For Business</a></li>
                  <li><a class="footer-link" href="#">Sales partners</a></li>
                  <li><a class="footer-link" href="#">Careers</a></li>
               </ul>
            </nav>
         </div>
      </footer>
      <script src="{% static 'js/main.js' %}"></script>
      {% block scripts %} {% endblock scripts %}
   </body>
</html>

templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block content %}
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" style="height: 400px;">
            <div class="carousel-item active">
              <img class="d-block w-100" src="http://127.0.0.1:8000/media/uploads/830-300-830x300-104.png" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="http://127.0.0.1:8000/media/uploads/830-300-830x300-742.png" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="http://127.0.0.1:8000/media/uploads/830-300-830x300-861.png" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-test-centered mt-6 mb-6">
            <h2 class="is-size-3">Sản phẩm nổi bật</h2>
        </div>

        {% for product in hot_product %}
            {% include 'product/parts/list_item.html' %}
        {% endfor %}
    </div>

    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-test-centered mt-6 mb-6">
            <h2 class="is-size-3">Sản phẩm mới nhất</h2>
        </div>

        {% for product in newest_products %}
            {% include 'product/parts/list_item.html' %}
        {% endfor %}
    </div>

{% endblock content %}

templates/core/post.html
{% extends 'core/base.html' %}


{% block content %}

    <h1>bài viết</h1>

    

{% endblock content %}